import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { LINKS } from "@/lib/constant";
import { NavLink } from "@/components/ui/navLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-no-repeat`}>
        <div>
          <button
            data-drawer-target="logo-sidebar"
            data-drawer-toggle="logo-sidebar"
            aria-controls="logo-sidebar"
            type="button"
            className="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
          >
            <span className="sr-only">Open sidebar</span>
            <svg
              className="w-6 h-6"
              aria-hidden="true"
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                clipRule="evenodd"
                fillRule="evenodd"
                d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"
              ></path>
            </svg>
          </button>

          <aside
            id="logo-sidebar"
            className="fixed top-0 left-0 z-40 w-80 h-full transition-transform -translate-x-full sm:translate-x-0"
            aria-label="Sidebar"
          >
            <div className="h-full px-3 py-4 overflow-y-auto bg-[#F5F5F5] dark:bg-gray-800">
              <div className="flex flex-col items-center h-40 w-full mt-[5rem]  mb-5">
                <Image
                  src="/assets/bedirhan.jpg"
                  alt="Bedirhan Kuzucu"
                  width={100}
                  height={100}
                  loading="lazy"
                  className="rounded-full  "
                />
                <span className="flex flex-col items-center">
                  <h1 className="mt-5 text-lg font-semibold">
                    Bedirhan Talha Kuzucu
                  </h1>
                  <h2 className="text-sm font-normal">Software Developer</h2>
                </span>
              </div>

              <div className="flex flex-col items-center w-full mt-[3.5rem]">
                <ul className="space-y-4 p-2 font-medium">
                  {LINKS.map((item, index) => (
                    <NavLink
                      icon={item.icon}
                      path={item.href}
                      label={item.label}
                      key={index}
                    />
                  ))}
                </ul>
              </div>
            </div>
          </aside>
        </div>
        <div className="p-5 h-screen sm:ml-80">{children}</div>
      </body>
    </html>
  );
}
